const users = [
  {
    id: 1,
    first_name: "Leoine",
    last_name: "Arthey",
    email: "larthey0@whitehouse.gov",
    gender: "Female",
    country: "Portugal",
  },
  {
    id: 2,
    first_name: "Carleton",
    last_name: "Marwood",
    email: "cmarwood1@yahoo.com",
    gender: "Male",
    country: "Portugal",
  },
  {
    id: 3,
    first_name: "Nollie",
    last_name: "Camilletti",
    email: "ncamilletti2@tripod.com",
    gender: "Female",
    country: "Indonesia",
  },
  {
    id: 4,
    first_name: "Lockwood",
    last_name: "Frift",
    email: "lfrift3@goodreads.com",
    gender: "Male",
    country: "Poland",
  },
  {
    id: 5,
    first_name: "Hadlee",
    last_name: "Dellenbrook",
    email: "hdellenbrook4@cbc.ca",
    gender: "Male",
    country: "Philippines",
  },
  {
    id: 6,
    first_name: "Jayne",
    last_name: "Guiden",
    email: "jguiden5@ezinearticles.com",
    gender: "Female",
    country: "Costa Rica",
  },
  {
    id: 7,
    first_name: "Mariann",
    last_name: "Manser",
    email: "mmanser6@deliciousdays.com",
    gender: "Female",
    country: "Canada",
  },
  {
    id: 8,
    first_name: "Dore",
    last_name: "Graeme",
    email: "dgraeme7@ihg.com",
    gender: "Female",
    country: "Indonesia",
  },
  {
    id: 9,
    first_name: "Aggi",
    last_name: "Newitt",
    email: "anewitt8@nasa.gov",
    gender: "Female",
    country: "China",
  },
  {
    id: 10,
    first_name: "Malinda",
    last_name: "Carletti",
    email: "mcarletti9@prnewswire.com",
    gender: "Female",
    country: "China",
  },
  {
    id: 11,
    first_name: "Vernon",
    last_name: "Wyborn",
    email: "vwyborna@360.cn",
    gender: "Male",
    country: "Sweden",
  },
  {
    id: 12,
    first_name: "Gar",
    last_name: "Bercevelo",
    email: "gbercevelob@vinaora.com",
    gender: "Male",
    country: "Philippines",
  },
  {
    id: 13,
    first_name: "Valle",
    last_name: "Renhard",
    email: "vrenhardc@themeforest.net",
    gender: "Male",
    country: "Japan",
  },
  {
    id: 14,
    first_name: "Danika",
    last_name: "Bugbird",
    email: "dbugbirdd@oakley.com",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 15,
    first_name: "Howie",
    last_name: "Bellini",
    email: "hbellinie@angelfire.com",
    gender: "Male",
    country: "Argentina",
  },
  {
    id: 16,
    first_name: "Mallory",
    last_name: "de Lloyd",
    email: "mdelloydf@symantec.com",
    gender: "Female",
    country: "Philippines",
  },
  {
    id: 17,
    first_name: "Bobby",
    last_name: "Antecki",
    email: "banteckig@ucsd.edu",
    gender: "Male",
    country: "Russia",
  },
  {
    id: 18,
    first_name: "Cthrine",
    last_name: "Oakenfall",
    email: "coakenfallh@mail.ru",
    gender: "Female",
    country: "Poland",
  },
  {
    id: 19,
    first_name: "Kaine",
    last_name: "Ionesco",
    email: "kionescoi@facebook.com",
    gender: "Male",
    country: "French Polynesia",
  },
  {
    id: 20,
    first_name: "Sheeree",
    last_name: "Caplin",
    email: "scaplinj@harvard.edu",
    gender: "Female",
    country: "China",
  },
  {
    id: 21,
    first_name: "Cloe",
    last_name: "Udey",
    email: "cudeyk@umn.edu",
    gender: "Female",
    country: "United States",
  },
  {
    id: 22,
    first_name: "Casey",
    last_name: "Martonfi",
    email: "cmartonfil@t.co",
    gender: "Male",
    country: "Indonesia",
  },
  {
    id: 23,
    first_name: "Yehudi",
    last_name: "Greneham",
    email: "ygrenehamm@mediafire.com",
    gender: "Male",
    country: "Pakistan",
  },
  {
    id: 24,
    first_name: "Valentine",
    last_name: "Barajas",
    email: "vbarajasn@goo.ne.jp",
    gender: "Female",
    country: "Ukraine",
  },
  {
    id: 25,
    first_name: "Celisse",
    last_name: "McPolin",
    email: "cmcpolino@unesco.org",
    gender: "Female",
    country: "Canada",
  },
  {
    id: 26,
    first_name: "Bearnard",
    last_name: "Tomasoni",
    email: "btomasonip@opera.com",
    gender: "Male",
    country: "Russia",
  },
  {
    id: 27,
    first_name: "Buddie",
    last_name: "Sycamore",
    email: "bsycamoreq@qq.com",
    gender: "Male",
    country: "China",
  },
  {
    id: 28,
    first_name: "Agnesse",
    last_name: "Petriello",
    email: "apetriellor@bandcamp.com",
    gender: "Female",
    country: "Kazakhstan",
  },
  {
    id: 29,
    first_name: "Freda",
    last_name: "Tessyman",
    email: "ftessymans@google.cn",
    gender: "Female",
    country: "France",
  },
  {
    id: 30,
    first_name: "Olly",
    last_name: "Greed",
    email: "ogreedt@columbia.edu",
    gender: "Male",
    country: "Finland",
  },
  {
    id: 31,
    first_name: "Ambrose",
    last_name: "Dive",
    email: "adiveu@engadget.com",
    gender: "Male",
    country: "Brazil",
  },
  {
    id: 32,
    first_name: "Ealasaid",
    last_name: "Collinge",
    email: "ecollingev@soundcloud.com",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 33,
    first_name: "Ximenes",
    last_name: "Michelle",
    email: "xmichellew@goodreads.com",
    gender: "Male",
    country: "China",
  },
  {
    id: 34,
    first_name: "Yvon",
    last_name: "MacLise",
    email: "ymaclisex@google.com.hk",
    gender: "Male",
    country: "Norway",
  },
  {
    id: 35,
    first_name: "Haven",
    last_name: "Purdy",
    email: "hpurdyy@photobucket.com",
    gender: "Male",
    country: "Argentina",
  },
  {
    id: 36,
    first_name: "Idalina",
    last_name: "Pattullo",
    email: "ipattulloz@umich.edu",
    gender: "Female",
    country: "Yemen",
  },
  {
    id: 37,
    first_name: "Tudor",
    last_name: "Rizzini",
    email: "trizzini10@cornell.edu",
    gender: "Male",
    country: "Canada",
  },
  {
    id: 38,
    first_name: "Kayle",
    last_name: "Wanden",
    email: "kwanden11@mtv.com",
    gender: "Female",
    country: "Brazil",
  },
  {
    id: 39,
    first_name: "Cristionna",
    last_name: "Shorbrook",
    email: "cshorbrook12@github.com",
    gender: "Female",
    country: "Brazil",
  },
  {
    id: 40,
    first_name: "Bartram",
    last_name: "Grinin",
    email: "bgrinin13@liveinternet.ru",
    gender: "Male",
    country: "Indonesia",
  },
  {
    id: 41,
    first_name: "Vasili",
    last_name: "Ivett",
    email: "vivett14@google.com",
    gender: "Male",
    country: "Thailand",
  },
  {
    id: 42,
    first_name: "Bobby",
    last_name: "Livoir",
    email: "blivoir15@amazonaws.com",
    gender: "Male",
    country: "Brazil",
  },
  {
    id: 43,
    first_name: "Desi",
    last_name: "Siuda",
    email: "dsiuda16@stumbleupon.com",
    gender: "Male",
    country: "Portugal",
  },
  {
    id: 44,
    first_name: "Lotta",
    last_name: "Lineen",
    email: "llineen17@japanpost.jp",
    gender: "Female",
    country: "Zambia",
  },
  {
    id: 45,
    first_name: "Corby",
    last_name: "Leckenby",
    email: "cleckenby18@ucsd.edu",
    gender: "Male",
    country: "Jordan",
  },
  {
    id: 46,
    first_name: "Sunny",
    last_name: "Farnin",
    email: "sfarnin19@pbs.org",
    gender: "Polygender",
    country: "Kazakhstan",
  },
  {
    id: 47,
    first_name: "Stanton",
    last_name: "Castiglione",
    email: "scastiglione1a@cloudflare.com",
    gender: "Male",
    country: "Russia",
  },
  {
    id: 48,
    first_name: "Dario",
    last_name: "Farebrother",
    email: "dfarebrother1b@blogspot.com",
    gender: "Male",
    country: "Venezuela",
  },
  {
    id: 49,
    first_name: "Zebulen",
    last_name: "Malafe",
    email: "zmalafe1c@oaic.gov.au",
    gender: "Male",
    country: "Cuba",
  },
  {
    id: 50,
    first_name: "Bill",
    last_name: "Leif",
    email: "bleif1d@thetimes.co.uk",
    gender: "Male",
    country: "Poland",
  },
];

// 0 - 4  limit - 5;
// 5 - 9
export const getUsers = function (page, limit) {
  let array = [];
  for (let i = (page - 1) * limit; i < page * limit && users[i]; i++) {
    array.push(users[i]);
  }
  return array;
};

export const getLength = function () {
  return users.length;
};
